version: '3.1'

services:
  
  mta-db:
    image: microsoft/mssql-server-windows-express
    environment: 
      - ACCEPT_EULA=Y
      - sa_password=DockerCon!!!
    networks:
      - app-net

  message-queue:
    image: nats:nanoserver
    networks:
      - app-net

  elasticsearch:
    image: sixeyed/elasticsearch:nanoserver
    networks:
      - app-net

  kibana:
    image: sixeyed/kibana:nanoserver
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - app-net

  homepage:
    image: sixeyed/mta-homepage
    networks:
      - app-net

  mta-app:
    image: sixeyed/mta-app:1.3
    ports:
      - "80:80"
    environment:
      - DB_CONNECTION_STRING=Server=mta-db;Database=ProductLaunch;User Id=sa;Password=DockerCon!!!;
      - HOMEPAGE_URL=http://homepage
    depends_on:
      - mta-db
      - message-queue
      - homepage
    networks:
      - app-net

  mta-save-handler:
    image: sixeyed/mta-save-handler
    environment:
      - DB_CONNECTION_STRING=Server=mta-db;Database=ProductLaunch;User Id=sa;Password=DockerCon!!!;
    depends_on:
      - mta-db
      - message-queue
    networks:
      - app-net

  mta-index-handler:
    image: sixeyed/mta-index-handler
    depends_on:
      - elasticsearch
      - message-queue
    networks:
      - app-net

networks:
  app-net:
    external:
      name: nat