version: '3.1'

services:
  
  mta-db:
    image: microsoft/mssql-server-windows-express
    environment: 
      - ACCEPT_EULA=Y
      - sa_password=DockerCon!!!
    networks:
      - app-net

  message-queue:
    image: nats:nanoserver
    #ports:
    #  - "4222:4222"
    networks:
      - app-net

  mta-app:
    image: ${dockerid}/mta-app:1.3
    ports:
      - "80:80"
    environment:
      - DB_CONNECTION_STRING=Server=mta-db;Database=ProductLaunch;User Id=sa;Password=DockerCon!!!;
    depends_on:
      - mta-db
      - message-queue
    networks:
      - app-net

  mta-save-handler:
    image: ${dockerid}/mta-save-handler
    environment:
      - DB_CONNECTION_STRING=Server=mta-db;Database=ProductLaunch;User Id=sa;Password=DockerCon!!!;
    depends_on:
      - mta-db
      - message-queue
    networks:
      - app-net

networks:
  app-net:
    external:
      name: nat